global:
  scrape_interval: 15s  # Set the interval at which Prometheus scrapes metrics

scrape_configs:
  - job_name: 'fastapi'
    static_configs:
      - targets: ['127.0.0.1:8000']  # This is the URL where FastAPI is running