names:
- aeroplane
- bicycle
- bird
- boat
- bottle
- bus
- car
- cat
- chair
- cow
- dog
- horse
- motorbike
- person
- pottedplant
- sheep
- sofa
- train
- tvmonitor
- diningtable
nc: 20
train: C:\Users\jdiaz\Desktop\DTU_MLOpsProject\data\processed
val: C:\Users\jdiaz\Desktop\DTU_MLOpsProject\data\processed
