program: src/object_detection/train.py
name: sweepdemo
project: DTU_MLOpsProject  # Ensure this is set to the correct project name
method: random  # Random search, you could also use grid search
metric:
  name: val/box_loss  # The metric we are trying to optimize
  goal: minimize  # Minimize box_loss
parameters:
  learning_rate:
    min: 0.0001
    max: 0.0002
  batch_size:
    values: [16, 32]
  epochs:
    value: 5
run_cap: 2
command:
  - ${env}
  - venv/Scripts/python.exe # Replace with the path to your virtual environment's Python
  - ${program}
  - ${args}