name: Continuous Integration Test

on:
  push:
    branches:
      - main

jobs:
  train_model:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Set up Google Cloud credentials
        run: |
          echo "${{ secrets.GOOGLE_CLOUD_KEY }}" | base64 --decode > $HOME/gcloud-key.json
          gcloud auth activate-service-account --key-file=$HOME/gcloud-key.json
          gcloud config set project ${{ secrets.GCP_PROJECT }}

      - name: Configure gcloud to pass credentials to gsutil
        run: |
          gcloud config set pass_credentials_to_gsutil true

      - name: Pull data using DVC
        run: |
          dvc pull data/processed/  # Specify the directory to pull

      - name: Train the model
        run: |
          python src/object_detection/train_.py  # Modify with your training script
