name: Pull Data from GCS with DVC

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  pull-data:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    # Set up Google Cloud SDK
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
        project_id: ${{ secrets.GCP_PROJECT }}
        service_account_key: ${{ secrets.GOOGLE_CLOUD_KEY }}

    # Authenticate with Google Cloud (gsutil)
    - name: Authenticate gsutil
      run: |
        echo "Setting up gsutil authentication..."
        echo "${{ secrets.GOOGLE_CLOUD_KEY }}" > gcp-key.json
        export GOOGLE_APPLICATION_CREDENTIALS=$PWD/gcp-key.json
        gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS
        gcloud config set pass_credentials_to_gsutil true

    # Test GCS bucket access (Verify if we can list files in the bucket)
    - name: Verify GCS access
      run: |
        echo "Testing GCS bucket access..."
        gsutil ls gs://${{ secrets.GCS_BUCKET_NAME }}/

    # Install dependencies (including DVC for GCS)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install dvc[gdrive,gcs]

    # Pull data with DVC
    - name: Pull data with DVC
      run: |
        echo "Pulling data with DVC..."
        dvc pull data/processed/

    # Clean up sensitive files (Remove service account key after use)
    - name: Clean up
      run: |
        echo "Cleaning up..."
        rm -f gcp-key.json
